/*
	RETURNS
		0 IF NO CHANGES WERE MADE BECAUSE THE NAME ALREADY EXISTS
		1 IF THE PROCEDURE WAS SUCCESSFUL
		3 IF THERE WAS AN ERROR
*/
CREATE PROCEDURE [dbo].[createPageObject]
	@id INT,
	@name VARCHAR(200),
	@orde INT
AS
BEGIN
	DECLARE 
		@RETURN INT
	IF((SELECT [name] FROM [dbo].[PageObject] WHERE [name] = @name) IS NULL)
	BEGIN TRY
		INSERT INTO [dbo].[PageObject]
			([name], [order])
		VALUES
			(@name, (SELECT TOP 1 [order] FROM [dbo].[PageObject] ORDER BY [order] DESC) + 1)
		SET @RETURN = 1
	END TRY
	BEGIN CATCH
		SET @RETURN = 3
	END CATCH
	
	RETURN @RETURN
END
GO
