/*
	RETURNS
		0 IF NO CHANGES WERE MADE BECAUSE THE NAME ALREADY EXISTS
		1 IF THE PROCEDURE WAS SUCCESSFUL
		3 IF THERE WAS AN ERROR
*/
CREATE PROCEDURE [dbo].[updatePageName]
	@id INT,
	@name VARCHAR(200)
AS
BEGIN
	DECLARE 
		@RETURN INT
	IF EXISTS(SELECT [name] FROM [dbo].[PageObject] WHERE id = @id)
	BEGIN TRY
		UPDATE [dbo].[PageObject]
		SET [name] = @name
		WHERE [id] = @id
		SET @RETURN = 1
	END TRY
	BEGIN CATCH
		SET @RETURN = 3
	END CATCH

	RETURN @RETURN
END
GO
